# this page including the format of the messages
START_SIGN = b'00'
COMMAND_SIGN = b'01'
UPLOAD_SIGN = b'02'
SUCCESS_MESSAGE = b'03'
USERNAME_FAILED_MESSAGE = b'04'
FAILED_MESSAGE = b'05'
START_MESSAGE = b'06'
EXIT_SIGN = b'07'
DOWNLOAD_SIGN = b'08'
CD_SIGN = b'09'
PORT = 3337